services:
  - type: web
    name: zcoder-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://zcoder-backend.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
